### ISSUE TITLE
Custom PCB details

### ISSUE THREAD

**Issue by piotrfila** [essele/rp2040-rmii#3]
HI!
I'm interested in trying to recreate this project, do you still have the project/gerber files for the PCB you used? I'm new to PCB design so not having to make one from scratch would be a huge help.

**Comment by essele** [comment]
Hi,

Unfortunately the only actual PCB I have files for is for a project that I'm not able to share. All of my testing was done with a pico and a modified simple LAN8720 breakout board as per the readme, so that should be easy to recreate. You can then use that to design a custom PCB. It is actually all pretty simple, there aren't any hidden gotchas.

Lee.
